version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: FaceID-Office
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: FaceID-Office
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: