version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: faceid_office_db
    environment:
      POSTGRES_USER: faceid_admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: faceid_office
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
